### ISSUE TITLE
Ubuntu Touch port

### ISSUE THREAD

**Issue by Hacker1245** [accumulator/Quickddit#63]
Would it be possible to port this app to Ubuntu Touch?

**Comment by jonnius** [comment]
I would like to help with packaging if someone did the changes in the code. Clickable desktop mode should help test even without a device. From first sight, Silica should be the only dependency that would need to be replaced.

**Comment by Hacker1245** [comment]
I could help with testing on an actual device.

**Comment by accumulator** [comment]
I'm open to pull requests :)

The C++ side is probably 99% ready for Ubuntu Touch, just a little bit of platform abstraction needed.

For the UI side, there's two possible approaches;
- totally separate QML tree for Ubuntu, similar to harmattan (needs a dedicated active maintainer)
- abstract the UI and provide implementations for Silica and Ubuntu, similar to what e.g Pure Maps has done (also might enable Android native and desktop clients)

Second option is trickier than it seems, since there's many many workarounds and tricks for weird Silica behaviour

**Comment by dano6** [comment]
I have my first implementation here https://github.com/dano6/Quickddit/tree/ubuntu-touch
This port using only Qt 5.9 and https://github.com/ubports/qqc2-suru-style/, no other dependencies, so you can test it with your PC.
@jonnius I would love to get help with packaging youtube-dl, I am not sure how to do it for implementing videos support.

**Comment by dano6** [comment]
I would love to hear any feedback. I can provide click packages or it is easy to compile for your PC.

**Comment by jonnius** [comment]
Works fine on my arm64 Xperia X running Ubuntu Touch. Great work! For help with packaging you can ping me on Telegram (@jonny) or Matrix (@jonny:ubports.chat).

**Comment by accumulator** [comment]
@dano6 Very nice, thanks for taking initiative! Also good to see you're using QQC2, this is IMO the proper way and could later also allow easier porting to an Android, or even desktop version.

**Comment by dano6** [comment]
I made PR #65

**Comment by accumulator** [comment]
Another bug closed, thanks @dano6 ;)
