### ISSUE TITLE
Add Github Sponsors support so we can give you a coffee ;)

### ISSUE THREAD

**Issue by JacekJagosz** [accumulator/Quickddit#91]
I would love to buy you a coffee, but you only accept bitcoin donations. Could you enable GitHub Sponsors, or any other way to give you a tip that doesn't use crypto?

**Comment by accumulator** [comment]
Thanks in advance ;) 
There's a Paypal link in the About page..

**Comment by Vistaus** [comment]
Please reconsider this. PayPal is good, but Reddit is now going to make developers pay to use their API, so we need a viable solution with people sponsoring this app. I don't want to lose this app…

**Comment by accumulator** [comment]
The problem is, voluntary donations will never cover the cost. The total donations sent over the 8 years I developed and maintained Quickddit can be compared to working less than half a day in a regular job :) 

SailfishOS is simply a too small ecosystem to even attempt creating a paid service, especially since they don't seem to be growing but stagnating.

Quickddit itself is open source and isn't going away, and you can compile a version with your own API keys if you want.

**Comment by Vistaus** [comment]
SailfishOS? I'm using Quickddit on Ubuntu Touch.

But I get that it's not going to cover all of the costs. However, I don't think Quickddit on Ubuntu Touch and SFOS makes too many requests, so Reddit should not charge you too much for the new API. I don't know about others, but I'm willing to donate up to 20 euros a month.

**Comment by Vistaus** [comment]
Seems like Reddit has done their math and the API calls are $2.50 per user. It should not be hard to raise that kind of money from Quickddit users. Like I said, I'm willing to donate up to 20 euros a month, so that already counts for 8 users. And maybe I'll pay some more if needed.

**Comment by Vistaus** [comment]
Alright, clearly you're not interested in receiving money. That's a first among devs! Or you're not good at communicating. Either way, it's sad to see a dev abandoning his app like this when there's at least one user willing to pay to save the app.

**Comment by accumulator** [comment]
I think you have a limited view of what needs to be done and you underestimate the overhead involved. Feel free to pick up the baton and maintain this app, it's open source after all.

W.r.t. communicating; I usually ignore bad behavior like condescending tone, or commenting with a strong air of entitlement, as if developers contributing their free time to open source should drop everything and immediately start working on their particular issue, but I'll make an exception this time.

**Comment by Vistaus** [comment]
Of course I have a limited view of what needs to be done. You're the dev, so you know best what needs to be done, but you didn't respond back to me at all until just now. Please tell me what more needs to be done. I'm not versed with C++/Qt, so I can't just take over.

I'm not trying to be condescending. I know you only do this in your free time, which is why I'm trying to convince you to take my money to save the app. That's all I'm saying. If you click on my profile, you can see that I'm a big open source contributor, so it's not like I don't know what open source means. And it was only my last post that was a bit harsh. You didn't respond to my ‘nicer’ posts from the days before either. So it's also a bit on you. I get that you don't have endless time, but the least you could've said was “thanks for your offer, I'll respond when I have time”. Of course, you're not obligated to do that, but it's the least you could've done for someone like me who's dedicated to saving this app. I'm not asking you to “drop everything to work on this issue”, I'm only asking you to communicate so that we can hopefully find a solution.

**Comment by Thaodan** [comment]
> Please reconsider this. PayPal is good, but Reddit is now going to make developers pay to use their API, so we need a viable solution with people sponsoring this app. I don't want to lose this app…

The volume is so low that likely the app will stay in the free tier. That said I think you would need continuos revenue for the enterprise tier api.

**Comment by Vistaus** [comment]
> > Please reconsider this. PayPal is good, but Reddit is now going to make developers pay to use their API, so we need a viable solution with people sponsoring this app. I don't want to lose this app…
> 
> The volume is so low that likely the app will stay in the free tier. That said I think you would need continuos revenue for the enterprise tier api.

AFAIK, the free tier is only for moderator tools and accessible apps. Quickddit is neither.

**Comment by Thaodan** [comment]
If I understood low volume apps will fall in the free tier. Quickddit as the only app for Sailfish OS in the enterprise tier sounds wrong.
Anyway that belongs to #104.

**Comment by Vistaus** [comment]
> If I understood low volume apps will fall in the free tier. Quickddit as the only app for Sailfish OS in the enterprise tier sounds wrong. Anyway that belongs to #104.

SailfishOS and Ubuntu Touch* (it's developed for Ubuntu Touch too and I'm using it on Ubuntu Touch)

But thanks, didn't know that! That's kind of a relieve.

**Comment by Vistaus** [comment]
Hmm, as far as I can see in the new API documentation, it's limited to 10 queries per minute per client id. Just spent a minute browsing on Quickddit and after 30 seconds, some posts wouldn't load anymore until the minute was up. So it is an issue still.

**Comment by Vistaus** [comment]
Now upvoting/downvoting posts is broken.

**Comment by Vistaus** [comment]
I still don't understand why Sponsors is such an issue. Aside from my proposed pledge, it's free to set up, so why not give it a try?

**Comment by Thaodan** [comment]
Heimen Stoffels ***@***.***> writes:

> Now voting is broken.

How? On my build voting works fine.

**Comment by Vistaus** [comment]
> How? On my build voting works fine.

It now displays an API error because the API has been changed on Reddit's end.

**Comment by Thaodan** [comment]
First of all create an issue if this is an  actual bug.
Second of all if you have an issue you need to provide logs (run
Quickddit in the terminal `harbour-quickddit > output.log` ).

**Comment by Vistaus** [comment]
It's not a bug, it's a change on Reddit's end as they are changing their API's. They introduced another change today that breaks voting, that is, it needs OAuth support now. And to fix this, this app needs more support to keep the development alive. Therefore, I keep posting here in order to motivate the dev to finally take my support pledge so we can save this app.

**Comment by Thaodan** [comment]
> It's not a bug, it's a change on Reddit's end as they are changing their API's. They introduced another change today that breaks voting. And to fix this, this app needs more support to keep the development alive. Therefore, I keep posting here in order to motivate the dev to finally take my support pledge so we can save this app.

No it's not. If it was a change on Reddit API's any build break including mine who use another API key.

If you keep posting here without noise that doesn't push the issue any further it won't help.
You can already donate via Paypal.

**Comment by Vistaus** [comment]
> No it's not. If it was a change on Reddit API's any build break including mine who use another API key.

There are reports from other tool and free tier API users on Reddit too.

> If you keep posting here without noise that doesn't push the issue any further it won't help. You can already donate via Paypal.

But PayPal isn't a recurring payment.

**Comment by Thaodan** [comment]
>> No it's not. If it was a change on Reddit API's any build break
>> including mine who use another API key.
>
> There are reports from other tool and free tier API users on Reddit too.

Can you post on the appropriate issue then?  The changes where supposed
to be active on the first of Juli, it does sound unrelated.

**Comment by Thaodan** [comment]
>> If you keep posting here without noise that doesn't push the issue
>> any further it won't help. You can already donate via Paypal.
>
> But PayPal isn't a recurring payment.

It's what you have, you can already donate.

Read his answers earlier.
